// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Apr  4 15:55:43 2011

#include <wx/wx.h>
#include <wx/image.h>
#include "dict.h"
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef MYFRAME_H
#define MYFRAME_H


// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxTextCtrl* text_word;
    wxButton* button_locate;
    wxPanel* panel_result;
    // end wxGlade

    DECLARE_EVENT_TABLE();
	
	Dict mDict;
public:
    virtual void OnLocate(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MYFRAME_H
