// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Apr  4 15:55:43 2011

#include "myframe.h"

// begin wxGlade: ::extracode
// end wxGlade



MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    text_word = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    button_locate = new wxButton(this, wxID_ANY, wxT("定位页数"));
    panel_result = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSIMPLE_BORDER|wxTAB_TRAVERSAL|wxFULL_REPAINT_ON_RESIZE);

    set_properties();
    do_layout();
    // end wxGlade
		
	label_location->SetLabel(_("正在加载..."));
	bool ok = mDict.Load("caoquanbei.dat");
	if(ok)
		label_location->SetLabel(_("加载完成"));
	else
		label_location->SetLabel(_("加载失败"));
}


BEGIN_EVENT_TABLE(MyFrame, wxFrame)
    // begin wxGlade: MyFrame::event_table
    EVT_TEXT_ENTER(wxID_ANY, MyFrame::OnLocate)
    EVT_BUTTON(wxID_ANY, MyFrame::OnLocate)
    // end wxGlade
END_EVENT_TABLE();


void MyFrame::OnLocate(wxCommandEvent &event)
{
	wxString word = text_word->GetValue();
	int page = mDict.LookUp(std::string(word.mb_str()));
	wxChar buf[100] = {0};
	if(page > 0)
	{
		wxSnprintf(buf, 100, _T("“%s”位于第%d页"), word.c_str(), page);
		label_location->SetLabel(buf);
	}
	else
		label_location->SetLabel(_("没有这个字耶"));
}


// wxGlade: add MyFrame event handlers


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("曹全碑定位器"));
    SetSize(wxSize(640, 400));
    text_word->SetMinSize(wxSize(400, 80));
    text_word->SetFont(wxFont(32, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("")));
    text_word->SetFocus();
    button_locate->SetMinSize(wxSize(200, 80));
    button_locate->SetFont(wxFont(32, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("")));
    panel_result->SetFont(wxFont(16, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("")));
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(text_word, 0, 0, 0);
    sizer_2->Add(button_locate, 0, 0, 0);
    sizer_1->Add(sizer_2, 1, wxEXPAND, 0);
    sizer_1->Add(panel_result, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}















